### PR TITLE
Fixed missing SQL utility from original psycopg2 package

### PR DESCRIPTION
**Pull request by limeschnaps**

### CODE REVIEW

**Review by lopuhin — COMMENTED** [review]
Thanks for the PR @limeschnaps , could you please port the tests as well?

**Comment by limeschnaps** [comment]
@lopuhin Hello! I've ported tests and also added some missing features

**Comment by lopuhin** [comment]
Thanks @limeschnaps - python 2.7 and pypy builds are failing on travis, at first sight it looks like it might be caused by the PR, could you please have a look?

**Comment by limeschnaps** [comment]
@lopuhin Yes, there was weird circular dependency and IDE was silent about it. Fixed

**Review by lopuhin — APPROVED** [review]
Looks great, thanks @limeschnaps 👍

**Comment by JCavallo** [comment]
Hello,

I had a compatibility problem because this utility was missing, and was happy to find it already solved. Thanks a lot @limeschnaps.

Is a new version already planned, or are we too close to the last release to consider it?

**Pull request merged**
